spring:
  application:
    name: AutoRefresh

server:
  port: 9000

spring.cloud.config.enabled: false
spring.cloud.config.import-check.enabled: false


management:
  endpoints:
    web:
      exposure:
        include: "*"


my:
  name: Discover fins mmnnnpkl